name: Lint and Format on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint -- --fix

    - name: Run Prettier
      run: npx prettier --write .

    - name: Configure Git
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Apply linting and formatting" --no-verify || echo "No changes to commit"
        git push origin HEAD:${{ github.head_ref }}
