name: Lint and Format on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm ci

    - name: Run Lint
      run: npm run lint -- --fix

    - name: Run Prettier
      run: npx prettier --write .

    - name: Configure Git
      run: |
        git config --global user.email "daszkowskiarek145@gmail.com"
        git config --global user.name "Arekk17"
        git config http.https://github.com/.extraheader "AUTHORIZATION: basic $(echo -n x-access-token:${{ secrets.PERSONAL_TOKEN }} | base64)"

    - name: Commit changes
      run: |
        git add .
        git commit -m "Apply linting and formatting" --no-verify || echo "No changes to commit"
      
    - name: Push Changes
      run: |
        git push https://${{ secrets.PERSONAL_TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:${{ github.head_ref }}
