name: Lint and Format on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Run Lint
      run: npm run lint -- --fix

    - name: Run Prettier
      run: npx prettier --write .

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply linting and formatting
        branch: ${{ github.head_ref }}
        commit_options: '--no-verify'
        file_pattern: '.'
